# Generated by Django 5.1.3 on 2025-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disease",
            options={
                "ordering": ["name"],
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="biological_control",
            field=models.TextField(blank=True, help_text="Biological control methods"),
        ),
        migrations.AddField(
            model_name="disease",
            name="causal_agent",
            field=models.CharField(
                blank=True, help_text="Bacteria, fungus, virus, etc.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="chemical_control",
            field=models.TextField(blank=True, help_text="Chemical treatment options"),
        ),
        migrations.AddField(
            model_name="disease",
            name="cultural_control",
            field=models.TextField(
                blank=True, help_text="Cultural practices for disease management"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="disease_cycle",
            field=models.TextField(
                blank=True, help_text="How the disease spreads and develops"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="economic_impact",
            field=models.TextField(
                blank=True, help_text="Yield loss, economic damage information"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="environmental_conditions",
            field=models.TextField(
                blank=True,
                help_text="Temperature, humidity requirements for disease development",
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="host_range",
            field=models.TextField(
                blank=True, help_text="Which crops/plant species are affected"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="images",
            field=models.JSONField(
                default=list, help_text="Image URLs for disease symptoms"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="integrated_management",
            field=models.TextField(blank=True, help_text="IPM strategies"),
        ),
        migrations.AddField(
            model_name="disease",
            name="prevention_priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("severe", "Severe"),
                ],
                default="moderate",
                help_text="Priority level for prevention",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="references",
            field=models.TextField(
                blank=True, help_text="Scientific references and sources"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
